### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by mukul9v** [Ross1337/SMSBotBypass#48]
Please add voice language option for English.

**Comment by Ross1337** [comment]
No. Do it yourself.

**Comment by tengri23** [comment]
Dolandırıcı bu adam

**Comment by mukul9v** [comment]
How

**Comment by mukul9v** [comment]
There is no tool available for voice converter

**Comment by mukul9v** [comment]
Its a request if u can do bcz everyone needs english

**Comment by Ross1337** [comment]
Just record the google tts voice using your computer as I did.

**Comment by mukul9v** [comment]
I dont have computer working on vps it will be really helpful if u can add english module thanks

**Comment by Ross1337** [comment]
I'll see if I have the time

**Comment by mukul9v** [comment]
Thanks

**Comment by mukul9v** [comment]
Should i send you text?

**Comment by Ross1337** [comment]
I'll do it the 3 or the 4th of this month. I just need a reminder.

**Comment by mukul9v** [comment]
So do you need text to convert to audio? I can send

**Comment by Ross1337** [comment]
I have everything I need.

**Comment by mukul9v** [comment]
Ok

**Comment by Zeph-ChasesBags** [comment]
yo @mukul9v can i get your discord username and can you help me with some stuff.

**Comment by Ross1337** [comment]
Here is the TTS : Welcome to our anti-fraud service, due to security precautions against online fraud, we may conduct checks. They allow us to authenticate our users correctly in order to fight online fraud, it will not take long. Our automatic system will assist you. If you have received the unique 6-digit password by text message, type it now. If you need time to receive the text message or enter the code, our automatic system will wait for you.

You can now yourself record and it to your bot
